pull_request_labels:
  - automation
  - l10n
files:
  - source: /*/src/main/res/values/strings.xml
    translation: /%original_path%-%android_code%/strings.xml
    translate_attributes: 0
    content_segmentation: 0
  - source: /fastlane/metadata/android/en-US/*.txt
    translation: /fastlane/metadata/android/%android_code%/%original_file_name%
